"""empty message

Revision ID: 0162e8b62fd1
Revises: 38f8b7aa45a7
Create Date: 2025-12-28 16:58:49.562428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0162e8b62fd1'
down_revision: Union[str, Sequence[str], None] = '38f8b7aa45a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('avatar', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'avatar')
    # ### end Alembic commands ###
