"""empty message

Revision ID: 2e7f08ee47cb
Revises: f4c332b42184
Create Date: 2025-12-27 12:08:57.093500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e7f08ee47cb'
down_revision: Union[str, Sequence[str], None] = 'f4c332b42184'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('password', sa.String(), nullable=False))
    op.drop_column('user_profiles', 'passwort')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('passwort', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user_profiles', 'password')
    # ### end Alembic commands ###
