"""engine = create_engine(DB_URL)

Revision ID: 5c7341f095d7
Revises: 9ccc03eb85f2
Create Date: 2026-01-03 20:23:26.774126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c7341f095d7'
down_revision: Union[str, Sequence[str], None] = '9ccc03eb85f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
